### ISSUE TITLE
no brainfuck

### ISSUE THREAD

**Issue by b0red-man** [x8c8r/SPWN-is-better-than#6]
no brainfuck so uh here
`++++++++++[>++++++++>++++++++>+++++++++>++++++++>+++>++++++++++>+++++++++++>+++>++++++++++>++++++++++>++++++++++++>++++++++++++>++++++++++>+++++++++++>+++>++++++++++++>++++++++++>++++++++++>+++++++++++>+++>+++++++>+++++++++++>++++++++++>++++++++++>+++++++++++>++++++++++>++++++++++++>++++++++++>+++++++++++<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-]>+++>>--->-->++>+++++>+++++>++>-->+>---->---->+>++++>++>---->++++>--->>++>---->++++>--->+++++>>++>--->->---<<<<<<<<<<<<<<<<<<<<<<<<<<<<[.>]`

i didnt make this code myself, im not mentally insane, i just found some string to brainfuck program online

**Comment by GachaYTB** [comment]
i added it so u can close this
